"""Write the animation-choice spec, as a normal File > Export target.

The spec is the authored intent behind an animated scenery part's dropdown: which
Actions are selectable, in what order, looping or one-shot, and under what label. The
build script consumes it (see modules/motiongraph_author.parse_spec).

This is deliberately a File > Export entry alongside Export MS2 / Export Manis rather
than a button on the object panel. It used to be the latter, with its own path
property, which meant a third place to click and remember - and forgetting it left a
stale spec, which the build then rejected with SPEC/ASSET MISMATCH. Using the standard
exporter pattern means the file dialog supplies the path, so no path property is
needed at all.

Pair it with Export Manis: the spec's durations are validated against the exported
.manis, so the two want writing together.
"""
import json
import logging
import os

import bpy

from plugin.mods.operators import specs_from_scenery
from plugin.mods.properties import effects_game_candidates

# v2: adds weight (Auto choice random-pool weight, null via "In random pool"
# off) and events (audio/VFX, authored via the Effects box + pose markers -
# see AnimEventItem). Both were already accepted on the read side
# (modules.motiongraph_author.parse_spec) before this exporter caught up
SPEC_VERSION = 2


def save(reporter, filepath=""):
	"""Write the active object's animation choices to `filepath` as JSON.

	Signature matches the other export targets: BaseOp binds `target` to the
	operator, so `reporter` is the operator and can report() to the UI.
	"""
	if not filepath:
		raise ValueError("no output path given")
	ob = bpy.context.object
	if ob is None:
		raise ValueError("no active object - select the object that owns the "
						 "animation choices")
	scenery = getattr(ob, "scenery", None)
	if scenery is None or len(scenery.anim_choices) == 0:
		raise ValueError(f"{ob.name} has no animation choices to export - add them "
						 f"in Object Properties > Cobra Asset information")

	fps = bpy.context.scene.render.fps
	# raises ValueError with a user-facing message naming the offending entry
	specs = specs_from_scenery(scenery, fps)

	payload = {
		"spec_version": SPEC_VERSION,
		"fps": fps,
		# NO sym_prefix and NO label_symbol. The loc symbol is generated by the
		# build from the TARGET asset's prefix (motiongraph_author.loc_symbol),
		# because only the target knows that prefix - when appending it must match
		# clips already in the asset, and a wrong guess yields a dropdown entry
		# that resolves to nothing and plays silently. The old "Loc Prefix" field
		# also defaulted to "InfoPanel_AnimationType_" with no asset segment, so
		# accepting the default shipped symbols that collide with any other mod
		# having a clip of the same name
		#
		# Clips are written BARE ("MyClip", not "MyProp$MyClip") for the same
		# reason: the build qualifies them against the target
		#
		# APPEND-ONLY: the build appends these in order and a placed prop stores the
		# resulting index, so this order IS the in-game order. Reordering or removing
		# a shipped entry silently repoints every instance already placed in a park
		# `loop`, NOT animation_flags. The UI authors a checkbox; the flags are an
		# engine bitfield derived from it (17 = Looping|FlagOnLoop, 16 = the same
		# with the Looping bit cleared - one bit apart). Writing the number meant the
		# spec round-tripped a boolean through a bitfield and back, and leaked an
		# engine detail into the one file a human reads. The emitter owns that
		# mapping; the spec states intent
		"clips": [{
			"clip": s.clip,
			"enum_name": s.enum_name,
			"label_text": s.label_text,
			"duration": round(s.duration, 6),
			"loop": s.loop,
			# null opts this entry out of the Auto choice's random pool entirely
			# (the "In random pool" toggle in the Effects box), rather than
			# giving it merely a low chance - only meaningful for a from-scratch
			# build; the append path (animspec) ignores it
			"weight": s.weight,
			# audio/VFX events authored in the Effects box, timed by this
			# choice's own Action pose markers - see events_from_choice. Empty
			# for a choice with none, matching parse_events' own "absent is
			# empty" rule rather than omitting the key
			"events": s.events,
		} for s in specs],
	}

	# Self-check through the SAME reader buildprop/animspec will use later,
	# before writing anything - a payload this exporter is happy with can
	# still be one parse_spec rejects. Measured case: an Action auto-renamed
	# by Blender's own collision handling ("Wobble.001") is a completely
	# ordinary thing to end up with (duplicate, copy-paste, apply to several
	# objects), and nothing here validated the clip name's charset - only
	# parse_spec does, and that only runs later, in a separate build step,
	# with an error that gives no hint the real cause is a stray dot in an
	# Action name back in Blender. Catching it here, in the same session
	# that can actually rename the Action, is the only place the fix is
	# still one click away
	from modules.motiongraph_author import parse_spec
	game = next(effects_game_candidates(bpy.context), None)
	try:
		parse_spec(payload, game)
	except ValueError as e:
		raise ValueError(f"export produced a spec the build would reject: {e}") from e

	os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
	with open(filepath, "w", encoding="utf-8") as f:
		json.dump(payload, f, indent="\t")
		f.write("\n")
	msg = f"Wrote {len(specs)} choice(s) to {filepath}"
	logging.info(msg)
	reporter.show_info(msg)
